version: '3.7'
services:
  mysql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=VK*23?ndfjO
      - POSTGRES_USER=app
      - POSTGRES_DB=db